name: .NET Core

on:
  push:
    branches: [ main, develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.110
    - name: Install dependencies
      run: dotnet restore
      working-directory: ./Conllu
    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: ./Conllu
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      working-directory: ./Conllu